[project]
name = "py-hinweis"
version = "0.1.0"
description = "Datastructure and Algorithms questions and answers"
readme = "README.md"
requires-python = ">=3.13.0"
dependencies = [
    "pytest>=8.3.5",
]
